# Generated by Django 3.2.12 on 2023-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderIdReference', models.CharField(max_length=64, unique=True)),
                ('oderDate', models.DateTimeField(auto_now=True)),
                ('orderItems', models.JSONField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isPaid', models.BooleanField(default=False)),
                ('isDeliverable', models.BooleanField(default=False)),
            ],
        ),
    ]
